import requests

url = 'https://webs.iiitd.edu.in/cgibin/vicmpred/vicmpred.pl'

sequences = ['MKTLFRTMVLGSLLALSANSYALSESEAEDMADLTAVFVFLKNDCGYQNLPNTQIRRALVFFAQQNQWDLSNYDSYNMKALGEDSYRDLSGINIPTAKKCKALARDSLSLLAYVK',
    'MKPKLTHALFLIPFLLLAGCSSSPKQAKNTKSHADMTIDGGSDDLIPVVAALHDQMHTWQGTPYEWGGTEQSGVDCSGFVWRTLKDRFNLPMERITTRELLHMGVRVNKRDLRPGDLVFFRTRAGMHVGFYDTDHNFLHASSSQGVMRSSLDNPYWESAFYQARRLPKEYNAQITMNSDTLHLAKNRR',
    'MSRRRGATLTKALLTVGCLLAAPLAQAISVGNLTFSLPAEADFASKRVVNNNKSARLYRIAVSAIDRPGGSEVRSRPVDGELLFAPRQLVLQAGESEYFKFYYHGPRDNRERYYRVSFREIPTRNLTRRSPTGGEVSMEPVVVMDTILVVRPREVQFKWSFDKVAGTVSNTGNTWFKLLIKPGCDSTEEEGDAWYLRPGDVVRQPALRQPGNHYLVYNDKFIKISDTCPLKPRPAE',
    'MLQSNEYFDGKVKSIGFTSSSTGRASVGVMAEGEYTFGTAQPEEMTVVSGALNVLLPGETEWKVYAAGEVFNVPGNSEFHLQVAEPTSYLCRYL',
    'MGLLNRIKMLWRAAVGSSYSWPAMDIVLPGERYLHLVGSIHMGTRDMAPPPAKLLKKIRQADALIVEADISGNETPFSNLPTYPPLAERLSDAQLSELEARAGELGLSVGLFDSQPLWQVAMVLQATQAQKLGLRPDYGIDYQLLMAARESNIAVMELEGADSQIALLRDLPDGGMALLEDTLTHWRTNARLLQVMIGWWLEQPPSRGAVSLPTTFSQSLYDVLMHQRNLAWRETLLALPPGRYVVAVGALHLYGEGNLPDMLT', 
    'MKKMLLIAMMAAGLVACTTSPAPKEDTKLKDAYSACINTAEGNPDKIEACQSVLNVLKKDKQHQQFTNQESVRVLDYQQCIQATRTGNDQAVKARCDQIWKEIRSNNTTH', 
    'MQRARCYLLGETAVVLELEPPVTLESQKRIWGLTQRLTDREEVVEVIPGMNNITVVLRRPQEMAWEAIDKLQRWWEESDALEPESREISIPVIYGGEAGPDLGDVARHSGLSEKQVVELHSSVEYMVWFLGFQPGFPYFGGLPEQLAMPRRAEPRVLVPAGSVGIGGSQTGIYPLATPGGWQLLGRTPLALFDPKREEPVLLRSGDRVRFVPQKEGVC',
    'MSALTGLPDNFTVQAFVILLSGGIFCMSSWIGINNGLQRLSKMVGWGAFLLPLVVLLVGPTEFITNNVINAVGLTTQNFLQMSLFTDPLGDGAFTRNWTVFYWLWWISYTPGVAMFVTRVSRGRKIKEVIWGLLLGSTAGCWFFFGVMESYAMHQFVNGVINVPQVMQTLGGETAVQQVLMSLPAGKLFLAAYLFVMIVFLASHMDAVAYTMAATSTRNLREGEDPDRGMRLFWCVVITLIPLSILFTGASLETMKTTVVLTALPFLAILLIKTGGFVRWLKQDYAHVPVHQIETHTPEPIIKAETLPVGAVLKGDGQSL', 
    'MPTQEAKAHRVGEWASLRNTSPEIAEAIFEVAHYDEKLAEQIWEEGSDEVLALAFAKTDKDSLFWGEQTIERKNV',
    'MIIYLHGFDSNSPGNHEKVMQLQFIDPDVRLISYSTRHPKHDMQHLLKEVDKMLQLTADDRPLICGVGLGGYWAERIGFLCDIRQAVFNPNLFPHENMEGKIDRPEEYADIATKCVTNFREKNRDRCLVVLSRQDEALDSQRSADLLHHYYEIIWDEEQTHKFKNISPHLQRLKAFKTTLG',
    'MELEEQVMGIIINAGQSRSLCYEALHAAKAGDFATADAKMQEAAHYSREAHLVQTQLIEADEGEGKTKMTLVMVHAQDHLMTSILAKELIAELIAIYRAQPLHA',
    'MNPYLQEVLDAHVLIERWLSHGEGSAEALMKRFAADFTMIPLSGEKMDYPTVSRFFHHAGGSRPGLDIVVDQMEIISEWHDGAAVLYRESQTLADSSQNVRWSTAIFQQAEGKIVWRHLQETRLG',
    'MKKVILASLLATMMSTSPVWATDSATAAPAAAATTQVQKEAADVLQVAVQGANAMRDIQFARLALFHGQPDSAKKLTDDAAALLAADDASWAKFVKTDAKAKMIADRYVIINASIALSEDYVATPEKESAIQSANEKLAKGDQKGAIDTLRLAGIGVIENQYLMPLNQTRKAVAQSQELLKAGKYYEANLVLKGAEEGIVVDSEMLVAGN',
    'MDTLAAIGRWLSKQHVVTWCVSREDELWCANAFYVYDPDTVAFYLLSEEHTRHGQMTGQRAKVAGTVNGQPKTVALIRGVQFKGEIRRLSGDEEARMRQRYVKRFPVARMLSAPVWEIRPDEIKFTDNTLGFGKKLHWRRDAGAEQA',
    'MTTYTFDFDEIAEQQDFYREFSRTFELAQDKVNNLDSLWDAVTGGLLPLPLDIEFIHLNDKQRRRFGALILLFDEAEEELEGELRFNARQA',
    'MSRSLLTNETSELDLLDQRPFDQTDFDILKSYEAVVDGLAMLIGSHCEIVLHSLQDLKCSAIRIANGEHTGRQIGSPITDLALRMLHDMTGADSSVSKCYFTRAKSGVLMKSVTIAIRNRDHRVIGLLCINMNLDVPFSQIMSTFIPPETPEVNSPVNFASSVDDLVAQTLEFTIEEVNADRSVSNNAKNRQIVLNLYEKGIFDIKDAINQVADRLNISKHTVYLYIRQFKSGDFQGLDK',
    ]

print('number of sequences =', len(sequences))
for i in range(len(sequences)):
    myobj = {'seqname': 'test',
        'seq': sequences[i],
    'file': '(binary)',
    'format': 'nformat',
    'approach': 1
    }
    x = requests.post(url, data = myobj)
    print(f"{i+1}. {sequences[i]}", end=' = ')
    if 'Cellular process' in x.text:
        print("Cellular process")
    elif "Metabolism Molecule" in x.text:
        print("Metabolism molecule")
    elif "Information and storage" in x.text:
        print('information and storage')
    else:
        print('Virulence')

    print()